// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `CommModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CommModule;

public interface SensorInterface extends Ice.Object,
                                         _SensorInterfaceOperations, _SensorInterfaceOperationsNC
{
    public static final long serialVersionUID = -8282315676731651912L;
}
